# Generated by Django 5.0 on 2024-04-25 08:39

import contract.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participantion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='项目参与顺序')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organ.participant', verbose_name='项目参与人')),
            ],
            options={
                'verbose_name': '项目参与',
                'verbose_name_plural': '项目参与',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(blank=True, max_length=100, null=True, verbose_name='项目编号')),
                ('finance_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='财务编号')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='项目名称')),
                ('project_type', models.CharField(blank=True, choices=[('JSFW', '技术服务'), ('JSZX', '技术咨询'), ('JSKF', '技术开发（合作）'), ('JSKS', '技术开发（委托）'), ('JSZR', '技术转让（转让）'), ('JSXK', '技术转让（许可）'), ('OTHER', '其他')], max_length=30, null=True, verbose_name='项目类别')),
                ('sign_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='签约日期')),
                ('start_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='计划结项日期')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='资金来源')),
                ('contract_fund', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='合同经费(万元)')),
                ('enter_year', models.IntegerField(blank=True, default=contract.models.current_year, null=True, verbose_name='登记年度')),
                ('enter_info', models.CharField(blank=True, max_length=50, null=True, verbose_name='登记情况')),
                ('end_info', models.CharField(blank=True, max_length=50, null=True, verbose_name='结项情况')),
                ('doc_transfer', models.CharField(blank=True, max_length=50, null=True, verbose_name='档案移交情况')),
                ('context', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('achievement_info', models.CharField(blank=True, max_length=50, null=True, verbose_name='成果简介')),
                ('status', models.CharField(blank=True, choices=[('Ongoing', '在研'), ('Conclusion', '结题')], default='Ongoing', max_length=10, null=True, verbose_name='项目状态')),
                ('authorize_units', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organ.org', verbose_name='委托单位')),
                ('director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directors', to='organ.participant', verbose_name='项目负责人')),
                ('participant', models.ManyToManyField(related_name='participants', through='contract.Participantion', to='organ.participant', verbose_name='项目参与人')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='序号')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='提取绩效日期')),
                ('fund', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='提取绩效(万元)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '提取绩效',
                'verbose_name_plural': '提取绩效',
            },
        ),
        migrations.AddField(
            model_name='participantion',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.project', verbose_name='项目'),
        ),
        migrations.CreateModel(
            name='FundState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='序号')),
                ('in_date', models.DateField(default=datetime.date.today, verbose_name='到账日期')),
                ('in_fund', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='到账经费(万元)')),
                ('tc_fund', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='统筹经费(万元)')),
                ('claim_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='认领日期')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '经费到账统筹',
                'verbose_name_plural': '经费到账统筹',
            },
        ),
        migrations.AlterUniqueTogether(
            name='participantion',
            unique_together={('project', 'participant')},
        ),
    ]
